# Generated by Django 5.2.8 on 2025-11-26 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('anio', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('kilometraje', models.IntegerField()),
                ('nombre_propietario', models.CharField(max_length=150)),
                ('telefono_propietario', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
    ]
